[[plugins]]
repo = 'jmcantrell/vim-virtualenv'
hook_add='''
let g:virtualenv_stl_format = '[%n]'
'''
on_ft = ["python", "python3", "djangohtml"]

[[plugins]]
repo = 'thinca/vim-quickrun'
on_event = 'QuickRun'
hook_add = '''
nnoremap <Space>r :QuickRun<CR>
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
hook_add = '''
nmap <Space>md <Plug>MarkdownPreview
'''

[[plugins]]
repo = 'gauteh/vim-cppman'
on_ft = ['cpp']



#
# [[plugins]]
# repo = 'lervag/vimtex'
# on_ft = ['tex']
# hook_add = '''
# let g:vimtex_compiler_latexmk = {
#       \ 'background': 1,
#       \ 'build_dir': '',
#       \ 'continuous': 1,
#       \ 'options': [
#       \    '-pdfdvi', 
#       \    '-verbose',
#       \    '-file-line-error',
#       \    '-synctex=1',
#       \    '-interaction=nonstopmode',
#       \],
#       \}
# let g:vimtex_view_general_viewer = '/mnt/c/Users/morim/AppData/Local/SumatraPDF/SumatraPDF.exe'
# let g:vimtex_quickfix_latexlog = {'default': 0}
# let g:vimtex_view_general_options = '-reuse-instance -forward-search @tex @line @pdf'
# let g:vimtex_view_general_options_latexmk = '--unique'
# " let g:vimtex_syntax_conceal = ""
# "" IME Setting
# " let &shell='/usr/bin/bash --login'
# " autocmd InsertLeave * :call system('${zenhan} 0')
# " autocmd CmdlineLeave * :call system('${zenhan} 0')
# "
# '''
